# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)
#
# platform :ios do
#   desc "Push a new beta build to TestFlight"
#   lane :beta do
# #     increment_build_number(xcodeproj: "Runner.xcodeproj")
#     build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
#     upload_to_testflight
#   end


# default_platform(:ios)
#
# platform :ios do
#   desc "Push a new beta build to TestFlight"
# lane :beta do
#   api_key = app_store_connect_api_key(
#     key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
#     issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
#     key_filepath: ENV["APP_STORE_CONNECT_API_KEY_PATH"]
#   )
#
#   build_app(
#     workspace: "Runner.xcworkspace",
#     scheme: "Runner"
#   )
#
#   upload_to_testflight(
#     api_key: api_key
#   )
#   end
# end

lane :beta do

  api_key = app_store_connect_api_key(
    key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
    issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
    key_filepath: ENV["APP_STORE_CONNECT_API_KEY_PATH"]
  )

  create_keychain(
    name: "ci_signing",
    password: ENV["MATCH_KEYCHAIN_PASSWORD"],
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: false
  )

  match(
    type: "appstore",
    readonly: true,
    api_key: api_key,
    keychain_name: "ci_signing",
    keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"]
  )

  build_app(
    workspace: "Runner.xcworkspace",
    scheme: "Runner",
    export_method: "app-store"
  )

  upload_to_testflight(
    api_key: api_key
  )

end


# match: This tells CI:
# Download the distribution certificate and App Store provisioning profile from Match and install them on this temporary macOS runner.