# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)
#
# platform :ios do
#   desc "Push a new beta build to TestFlight"
#   lane :beta do
# #     increment_build_number(xcodeproj: "Runner.xcodeproj")
#     build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
#     upload_to_testflight
#   end


# default_platform(:ios)
#
# platform :ios do
#   desc "Push a new beta build to TestFlight"
# lane :beta do
#   api_key = app_store_connect_api_key(
#     key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
#     issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
#     key_filepath: ENV["APP_STORE_CONNECT_API_KEY_PATH"]
#   )
#
#   build_app(
#     workspace: "Runner.xcworkspace",
#     scheme: "Runner"
#   )
#
#   upload_to_testflight(
#     api_key: api_key
#   )
#   end
# end



default_platform(:ios)

platform :ios do

  desc "Build and upload iOS app to TestFlight"

  lane :beta do

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: ENV["APP_STORE_CONNECT_API_KEY_PATH"]
    )

    match(
      type: "appstore",
      readonly: true,
      api_key: api_key
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )

    upload_to_testflight(
      api_key: api_key
    )

  end

end


# match: This tells CI:
# Download the distribution certificate and App Store provisioning profile from Match and install them on this temporary macOS runner.