# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:android)
#
# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end
#
#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
#
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end
#
#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end

# default_platform(:android)
#
# platform :android do
#
#   desc "Build a signed Android App Bundle"
#   lane :build do
#     gradle(task: "clean")
#     gradle(
#       task: "bundle",
#       build_type: "Release"
#     )
#   end
#
# end



# default_platform(:android)
#
# platform :android do
#
#   desc "Run Android tests"
#   lane :test do
#     gradle(
#       task: "test"
#     )
#   end
#
#   desc "Build a signed Android App Bundle and deploy it to play store internals"
#   lane :deploy_internal do
#     gradle(
#       task: "clean"
#     )
#
#     gradle(
#       task: "bundle",
#       build_type: "Release"
#     )
#
#   upload_to_play_store(
#     track: "internal",
#     aab: "../build/app/outputs/bundle/release/app-release.aab"
#   )
#   end
#
# end




default_platform(:android)

platform :android do

  desc "Run Android tests"
  lane :test do
    gradle(
      task: "test"
    )
  end

  desc "Build a signed Android App Bundle"
  lane :build do
    gradle(task: "clean")

    gradle(
      task: "bundle",
      build_type: "Release",
      properties: {
         "flutter.versionName" => ENV["FLUTTER_VERSION_NAME"],
         "flutter.versionCode" => ENV["FLUTTER_VERSION_CODE"]
       }
    )
  end

  desc "Build and deploy to Google Play Internal Testing"
  lane :deploy_internal do
    build

    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

end




#  (pass version to gradle) maintaining version explicitly, github extract version from pubspec.yaml then give it to fastlane ( in workflow ), fastlane pass it to gradle during build like here
#     properties: {
#          "flutter.versionName" => ENV["FLUTTER_VERSION_NAME"],
#          "flutter.versionCode" => ENV["FLUTTER_VERSION_CODE"]
#          }