name: iOS CD

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    branches:
      - auto_development

jobs:
  ios-cd:

    runs-on: macos-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'
          channel: stable
          cache: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          working-directory: ios
          bundler-cache: true

      - name: Flutter dependencies
        run: flutter pub get

      - name: Install CocoaPods dependencies
        working-directory: ios
        run: pod install

      - name: Configure SSH for Match
        env:
          MATCH_GIT_SSH_PRIVATE_KEY: ${{ secrets.MATCH_GIT_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "$MATCH_GIT_SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Create App Store Connect API key
        run: |
          echo '${{ secrets.APP_STORE_CONNECT_API_KEY }}' > ios/app_store_connect_api_key.p8
          chmod 600 ios/app_store_connect_api_key.p8

      - name: Install iOS Fastlane dependencies
        working-directory: ios
        run: |
          bundle install
          bundle exec fastlane --version

      - name: Deploy to TestFlight
        working-directory: ios
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}

          APP_STORE_CONNECT_API_KEY_PATH: ${{ github.workspace }}/ios/app_store_connect_api_key.p8

        run: |
          bundle exec fastlane ios beta

      - name: Cleanup secrets
        if: always()
        run: |
          rm -f ios/app_store_connect_api_key.p8
          rm -f ~/.ssh/id_ed25519